export const localities=[
    "Balewadi",
  "Baner",
  "Chandan Nagar",
  "Deccan Gymkhana",
  "Hadapsar",
  "Hinjewadi",
  "Kalyani Nagar",
  "Katraj",
  "Keshav Nagar",
  "Kharadi",
  "Kothrud",
  "Koregaon Park",
  "Narhe",
  "Pimpri Chinchwad",
  "Shivaji Nagar",
  "Swargate",
  "Viman Nagar",
  "Wakad",
]

